name: TrioSim

on: push

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build
        run: go build ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          args: --timeout=10m

      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Unit Test
        run: ginkgo -r
